# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgata-va <fgata-va@student.42madrid>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/07 14:55:24 by fgata-va          #+#    #+#              #
#    Updated: 2022/03/08 19:32:41 by fgata-va         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
    mariadb:
        build: ./requirements/mariadb/
        restart: unless-stopped
        volumes:
            - type: volume
              source: dbdata
              target: /var/lib/mysql
              volume:
                  nocopy: true
    nginx:
        build: ./requirements/nginx/
        ports:
            - "443:443"
        restart: unless-stopped
        volumes:
            - ./${CERTS_}:/etc/ssl/
volumes:
    dbdata:
