# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fgata-va <fgata-va@student.42madrid>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/07 14:55:24 by fgata-va          #+#    #+#              #
#    Updated: 2022/03/08 19:32:41 by fgata-va         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
    mariadb:
        env_file: .env
        build: ./requirements/mariadb/
        restart: unless-stopped
        volumes:
            - type: volume
              source: dbdata
              target: /var/lib/mysql
        networks:
          - php-mariadb
    php-fpm:
        env_file: .env
        depends_on:
          - mariadb
        build: ./requirements/wordpress/
        restart: unless-stopped
        volumes:
          - type: volume
            source: wpdata
            target: /usr/share/webapps/wordpress
        networks:
          - php-nginx
          - php-mariadb
    nginx:
        depends_on:
          - mariadb
          - php-fpm
        build: ./requirements/nginx/
        ports:
            - "443:443"
        restart: unless-stopped
        volumes:
            - ./${CERTS_}:/etc/ssl/
            - type: volume
              source: wpdata
              target: /var/www/wordpress
              volume:
                nocopy: true
        networks:
          - php-nginx
volumes:
    dbdata:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/${USER}/data/db_volume
    wpdata:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/${USER}/data/wp_volume
networks:
    php-nginx:
    php-mariadb:
